[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=D:/Project/blockchain/foundry/stablecoin_defi/lib/openzeppelin-contracts/contracts/",
    "@forge-std/=D:/Project/blockchain/foundry/stablecoin_defi/lib/forge-std/src/",
    "@chainlink/contracts/=D:/Project/blockchain/foundry/stablecoin_defi/lib/chainlink-brownie-contracts/contracts/",
]

[invariant]
runs = 128
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
